In [2]:
import os, xarray as xr, numpy as np, pandas as pd, dask, random, netCDF4
import cartopy.crs as ccrs, matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable

from datetime import datetime as dt, timedelta
import datetime, time

import importlib
import matplotlib.patches as mpatches
import gc
from matplotlib.gridspec import GridSpec
dask.config.set({"array.slicing.split_large_chunks": False})
import sys
sys.path.insert(1, '/home/data/lab_hardik/udf/')

import h5netcdf

ERROR 1: PROJ: proj_create_from_database: Open of /home/lab_hardik/my_conda/share/proj failed


In [3]:
import composite_funcs
import grad_funcs
importlib.reload(composite_funcs)
from composite_funcs import *
from grad_funcs import *

[30. 60. 90.]
[10. 30. 50.]
$\mathregular{\mathcal{S}'_{x}}$
["$u'$", "$v'$", "$w'$", "$\\mathcal{S}'_x$", "$\\mathcal{S}'_y$", "$\\mathcal{S}'_z$", '${u̅}$', '${v̅}$', '${w̅}$', '$\\mathcal{S}̅_x$', '$\\mathcal{S}̅_y$', '$\\mathcal{S}̅_z$']
dict_values(["$u'$$\\mathcal{S}'_x$", "$v'$$\\mathcal{S}'_y$", "$w'$$\\mathcal{S}'_z$", "$u'$$\\mathcal{S}̅_x$", "$v'$$\\mathcal{S}̅_y$", "$w'$$\\mathcal{S}̅_z$", "${u̅}$$\\mathcal{S}'_x$", "${v̅}$$\\mathcal{S}'_y$", "${w̅}$$\\mathcal{S}'_z$", '${u̅}$$\\mathcal{S}̅_x$', '${v̅}$$\\mathcal{S}̅_y$', '${w̅}$$\\mathcal{S}̅_z$'])
["$v'$$\\mathcal{S}̅_y$", "$w'$$\\mathcal{S}̅_z$", "${u̅}$$\\mathcal{S}'_x$"]
["$u'$$\\mathcal{S}'_x$", "$v'$$\\mathcal{S}'_y$", "$w'$$\\mathcal{S}'_z$"]
['${u̅}$$\\mathcal{S}̅_x$', '${v̅}$$\\mathcal{S}̅_y$', '${w̅}$$\\mathcal{S}̅_z$']
["$u'$$\\mathcal{S}̅_x$", "${v̅}$$\\mathcal{S}'_y$", "${w̅}$$\\mathcal{S}'_z$"]
[30. 60. 90.]
[10. 30. 50.]


In [4]:
dir_out = '/home/data/lab_hardik/heatwaves/ERA5/analyses/phase_relations/data/'

In [5]:
dat_dir = '/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files/'
# files = [s for s in os.listdir(dat_dir) if 'Apr' in s]
# # files.sort(key = os.path.getctime)
# files

In [6]:
# tst = xr.open_dataset('/home/data/lab_hardik/data/ERA5/climatology/t_3D/dly_clmtlgy_stdPlevs_prmnsn_temperature_1980_2022_wFeb.nc')
# tst.close()

importlib.reload(composite_funcs)
from composite_funcs import *

[30. 60. 90.]
[10. 30. 50.]


In [7]:

prepare_files(variable='u') # 1980 to 2022
prepare_files(variable='v') # 1980 to 2022
prepare_files(variable='t') # 1980 to 2022
prepare_files(variable='z') # 1995 to 2022


5246
['era5_u_component_of_wind_1980_3_1.nc', 'era5_u_component_of_wind_1980_3_2.nc', 'era5_u_component_of_wind_1980_3_3.nc', 'era5_u_component_of_wind_1980_3_4.nc', 'era5_u_component_of_wind_1980_3_5.nc', 'era5_u_component_of_wind_1980_3_6.nc']
5246
['era5_v_component_of_wind_1980_3_1.nc', 'era5_v_component_of_wind_1980_3_2.nc', 'era5_v_component_of_wind_1980_3_3.nc', 'era5_v_component_of_wind_1980_3_4.nc', 'era5_v_component_of_wind_1980_3_5.nc', 'era5_v_component_of_wind_1980_3_6.nc']
5246
['era5_temperature_1980_3_1.nc', 'era5_temperature_1980_3_2.nc', 'era5_temperature_1980_3_3.nc', 'era5_temperature_1980_3_4.nc', 'era5_temperature_1980_3_5.nc', 'era5_temperature_1980_3_6.nc']
3416
['era5_geopotential_1995_3_1.nc', 'era5_geopotential_1995_3_2.nc', 'era5_geopotential_1995_3_3.nc', 'era5_geopotential_1995_3_4.nc', 'era5_geopotential_1995_3_5.nc', 'era5_geopotential_1995_3_6.nc']


In [8]:
ds_z_1980_1994 = prepare_z_ds(year_min = 1980, year_max = 1994)

['era5/.zgroup', 'era5/.zmetadata', 'era5/era5']


/home/lab_hardik/my_conda/lib/python3.9/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
/home/lab_hardik/my_conda/lib/python3.9/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
/home/lab_hardik/my_conda/lib/python3.9/site-packages/paramiko/transport.py:243: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
/home/data/lab_hardik/udf/composite_funcs.py:62: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanose

In [9]:
ds_z_1980_1994 = \
ds_z_1980_1994.sel(isobaricInhPa = slice(600,900))
# .rechunk({'isobaricInhPa':1, 'longitude':720})

In [10]:
os.chdir(dat_dir)

In [11]:
import variables
from variables import *

In [12]:
dat_dir

'/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files/'

In [13]:
def compute_M(ds = xr.Dataset()): #ds_brnch_path1
    
    R = 287
    Rearth = 6378*10**3
    steps_x = 4*10
    del_lambda = 0.25*np.pi/180
    del_phi = 0.25*np.pi/180

    ds = compute_zdiff_fields(ds)
    ds['density'] = (ds['isobaricInhPa']*100)/(287*ds['t'])

    Axy_2 = Rearth**2*del_lambda*(
        np.sin((Rlat.latitude + 0.25)*np.pi/180) - np.sin(Rlat.latitude*np.pi/180)
    )
    M = (Axy_2*ds['z_diff_down']/g*.5*(ds['density'] + ds['density'].shift(isobaricInhPa=-1)))\
    .sel(latitude=slice(24,30.75), longitude=slice(68,77.75))
    
    return M


In [14]:
def plot_samples(ds, save_str = ''):
#     global fig, ax
    # num_plots = 10 if df.shape[0]>=10 else df.shape[0]
    # num_plots = 10 if len(ds.date)>=10 else len(ds.date)

    # num_plots = int(np.ceil(len(ds.date)/2)*2)

    num_plots = len(ds.date)

    nrow = int(np.ceil(num_plots/2))

    fig, ax = plt.subplots(
        nrow,2, figsize=(16, nrow*4), sharey=True, subplot_kw={'projection': ccrs.PlateCarree()}
    )

    for i in range(num_plots):
        r = bicol_panel_rownum(i)
        c = bicol_panel_colnum(i)
        print('rowunm',r)
        print('colnum',c)

        tot_flx = df.Net_Adv.iloc[i].round(0)
        dse_anom = df.dse_anom.iloc[i].round(0)

        da_plt = ds[dse_var].isel(date = i)#.mean(['date'])#.compute()
        da_cont = ds[z_var].isel(date = i)#.mean(['date'])#.compute()
        da_u = (ds[u_var]).isel(date = i)#.mean(['date'])#.compute()
        da_v = (ds[v_var]).isel(date = i)#.mean(['date'])#.compute()
        # da_u = ds['adv_flx_x'].mean(['date']).compute()
        # da_v = ds['adv_flx_y'].mean(['date']).compute()

        # vmin = np.nan; vmax=np.nan
        inner_plot_composite(
            da_plt = da_plt, da_cont = da_cont, da_u = da_u, da_v = da_v, xmin=0, xmax=120, ymin=10, ymax=65, 
            cont_divisions=20, coarsen_pts=8,
            t_type = 'dse_anom',scale_quiv= 70, 
            i = r, j = c, ax=ax[r,c], 
            title_str = 'dse_anom = {}, dse_flx = {}, date = {}'.format(dse_anom, tot_flx, str(df.date.iloc[i].date()))
            )
    plt.tight_layout()
    
    if save_str != '':
        plt.savefig('/home/data/lab_hardik/heatwaves/ERA5/analyses/phase_relations/{}'.format(save_str))


In [15]:
import re 
def starts_with_substring_and_number(s, substring): 
    pattern = rf"^{re.escape(substring)}\d+" 
    return re.match(pattern, s) is not None 
# Example usage 
string = "prefix12345" 
substring = "prefix" 
result = starts_with_substring_and_number(string, substring) 
print(result) 
# Output: True


True


In [16]:
def read_files_comp(dates = list(), sample=np.nan, two_day_averaging = True):
    global ds_z_comp, ds_v_comp, ds_u_comp, ds_t_comp, brnch_dates, brnch_dates2
#     brnch_dates = df.date.sample(10 if df.shape[0] >= 10 else df.shape[0])
    print('sample', sample)

    if sample != sample: 
        print('sample == np.nan')
        brnch_dates = dates
    else: 
        brnch_dates = random.sample(dates, sample if df.shape[0] >= sample else df.shape[0])

    print('len(brnch_dates)', len(brnch_dates))

    if two_day_averaging == True: 
        brnch_dates2 = ([s - timedelta(days=1) for s in brnch_dates] + brnch_dates)
        print('len(brnch_dates2)', len(brnch_dates2))
    else: 
        brnch_dates2 = brnch_dates
    
    press = slice(900,600)

    ds_z_comp = filt_comp_files(
        variable='z', dates = brnch_dates2, press=press, 
        ds_z_1980_1994 = ds_z_1980_1994.sortby('isobaricInhPa', ascending=False), 
        ymin=10, ymax=60, xmin=0, xmax=120
    )
    
    ds_v_comp = filt_comp_files(variable='v', dates = brnch_dates2, press= press, ymin=10, ymax=60, xmin=0, xmax=120)
    ds_u_comp = filt_comp_files(variable='u', dates = brnch_dates2, press=press, ymin=10, ymax=60, xmin=0, xmax=120)
    ds_t_comp = filt_comp_files(variable='t', dates = brnch_dates2, press=press, ymin=10, ymax=60, xmin=0, xmax=120)

In [17]:
def add_anoms():
    global ds_z_comp, ds_v_comp, ds_u_comp, ds_t_comp
    
    press = slice(900,600)
    ds_z_comp = create_anoms(variable='z', press=press, ds=ds_z_comp, clmt_file_map = rolling_clmt_file_map)
    ds_t_comp = create_anoms(variable='t', press=press, ds=ds_t_comp, clmt_file_map = rolling_clmt_file_map)
    ds_u_comp = create_anoms(variable='u', press=press, ds=ds_u_comp, clmt_file_map = rolling_clmt_file_map)
    ds_v_comp = create_anoms(variable='v', press=press, ds=ds_v_comp, clmt_file_map = rolling_clmt_file_map)

    ds_t_comp['t_clmt'] = ds_t_comp['t'] - ds_t_comp['t_anom_10D']
    ds_z_comp['z_clmt'] = ds_z_comp['z'] - ds_z_comp['z_anom_10D']

    ds_u_comp['u_clmt'] = ds_u_comp['u'] - ds_u_comp['u_anom_10D']
    ds_v_comp['v_clmt'] = ds_v_comp['v'] - ds_v_comp['v_anom_10D']

In [18]:
def merge_branch_data(two_day_averaging = True):
    ymin=10
    ymax=60
    xmin=0
    xmax=120
    
    global ds_v_comp, ds_u_comp, ds_z_comp, ds_t_comp, ds_brnch_path1, ds_brnch, ds_brnch2, da_dse_anom_Lag1
    
    ds_brnch_path1 = xr.combine_by_coords(
        [ds_v_comp, ds_u_comp, ds_z_comp, ds_t_comp], 
        join='inner', combine_attrs='drop_conflicts'
    )\
    .sel(latitude=slice(ymax,ymin), longitude=slice(xmin,xmax)).chunk({'latitude':241,'longitude':481})

    ds_brnch_path1['density'] = (ds_brnch_path1['isobaricInhPa']*100)/(287*ds_brnch_path1['t'])
    
    gc.collect()

#     Rlat = Rlat_fn(ds = ds_brnch_path1)
#     M = compute_M(ds = ds_brnch_path1)

    ds_brnch = ds_brnch_path1.weighted(ds_brnch_path1['density']).mean('isobaricInhPa').sortby(['latitude','longitude','date'])
    
#     for variable in list(ds_brnch.data_vars):
#         print(variable)
#         ds_brnch[variable] = vert_MassAve_qty(
#             M = M, 
#             qty = ds_brnch[variable], 
#             p_low=600, p_high=900
#         ).compute()
    
    print('ds_brnch.dims', ds_brnch.dims)

    ds_brnch['dse'] = 1005*ds_brnch['t'] + ds_brnch['z']
    ds_brnch['dse_anom'] = 1005*ds_brnch['t_anom_10D'] + ds_brnch['z_anom_10D']
    ds_brnch['dse_clmt'] = 1005*ds_brnch['t_clmt'] + ds_brnch['z_clmt']
    ds_brnch['dse_anom_Lag1'] = ds_brnch['dse_anom'].shift(date=1)
    
    da_dse_anom_Lag1 = ds_brnch['dse_anom_Lag1'].sel(date = brnch_dates)

    if two_day_averaging == True:
        ds_brnch = ds_brnch.sortby('date')
        ds_brnch2 = 0.5*(ds_brnch + ds_brnch.shift(date = 1))

        ds_brnch2 = xr.merge(
            [
                ds_brnch2[[s for s in list(ds_brnch2.data_vars) if 'Lag1' not in s]].sel(date = brnch_dates), 
                da_dse_anom_Lag1, 

            ])

        print('len(ds_brnch.date)',len(ds_brnch.date))
        print('len(ds_brnch2.date)',len(ds_brnch2.date))
        
#         da_z_tst0 = client.scatter(ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[0]))
#         da_z_tst1 = client.scatter(ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]))
#         da_z_tst2 = client.scatter(ds_brnch2['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]))

#         def myfunc(dask_array):
#             return dask_array.compute()

#         future0 = client.submit(myfunc, da_z_tst0)
#         a0 = client.gather(future0)

        a0 = ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[0]).values
        a1 = ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]).values
        a2 = ds_brnch2['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]).values
        
#         future1 = client.submit(myfunc, da_z_tst1)
#         a1 = client.gather(future1)# ds_brnch['z_anom_10D'].sel(date = ds_brnch.date[1])[20,20].values
        
#         future2 = client.submit(myfunc, da_z_tst2)
#         a2 = client.gather(future2) #ds_brnch2['z_anom_10D'].sel(date = ds_brnch.date[1])[20,20].values

        print(0.5*(a0+a1))
        print(a2)

        if np.round(0.5*(a0+a1),3) != np.round(a2,3):
            return 'incorrect 2D ave'
    else:
        ds_brnch2 = ds_brnch

    print(ds_brnch2.dims)
    print(ds_brnch2.data_vars)
    
#     del ds_v_comp, ds_u_comp, ds_z_comp, ds_t_comp
    gc.collect()
    gc.collect()
    
    return ds_brnch, ds_brnch2

def write_nc(ds, dir_out = dir_out, file_out = str):
    ds.to_netcdf(dir_out + file_out)

In [19]:
importlib.reload(grad_funcs)
from grad_funcs import *

importlib.reload(composite_funcs)
from composite_funcs import *


[30. 60. 90.]
[10. 30. 50.]


In [20]:
dat_dir

'/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files/'

In [55]:
# files0 = [s for s in os.listdir(dat_dir) if s.startswith('Apr_pos') and 'v2' in s 
#          and 'nl_' not in s # and 'nl2' not in s
#         and 'amplif_nl_xNL' not in s # this was from an old run
#          and 'posbg2_decay_nl_xNL' not in s # posbg2 is included in posbg
#         ]

# files0 = ["Apr_posbg_decay_nl2_yNL_v2.csv"]

files0 = ["Apr_posbg_decay_nl1_xNL_v2.csv"]
files0 = ['Apr_posbg_decay_nlsat_yNL_v2.csv']
files0=["Apr_posbg_decay_nl2_yNL_v2.csv"]
files0.sort(key = lambda s: (s.split('_')[1], s.split('_')[2], s.split('_')[3]))
print(len(files0))

files0


1


['Apr_posbg_decay_nl2_yNL_v2.csv']

In [56]:
files = files0

In [57]:
# files = [s for s in files0 if s.endswith("decay_ql_xyip_v2.csv") or s.endswith("decay_nl1_yNL_v2.csv")]
# files

## New data prep section

In [58]:
importlib.reload(composite_funcs)
from composite_funcs import *

In [59]:
pd.read_csv(files[0], parse_dates=['date'])

date  $u'$$\mathcal{S}'_x$  $v'$$\mathcal{S}'_y$  \
0 2018-04-18           -447.920768           -107.081774   
1 2007-04-01           -491.043593          -1042.244893   
2 2011-04-29           -214.704113           -956.098205   
3 2003-04-13           -276.302201          -1106.881364   
4 2002-04-29            371.138501          -1719.281838   
5 2022-04-12             86.293640          -1362.389329   

   $w'$$\mathcal{S}'_z$  $v'$$\mathcal{S}̅_y$  $w'$$\mathcal{S}̅_z$  \
0            -10.163428           -110.394913            893.855788   
1            370.839153           1965.431873           -341.261646   
2             85.732790            551.894457            241.836896   
3             48.271706            797.552748            242.269162   
4             69.068122          -1117.687922            536.627849   
5            232.801511           1378.579970           -669.498137   

   ${u̅}$$\mathcal{S}'_x$      T_main       NL_sum  x_contrib_NL  ...  \
0             -783.229455    0.231421  -565.165970     79.254731  ...   
1            -1502.587454  121.582773 -1162.449333     25.788376  ...   
2             -702.619547   91.111806 -1085.069528     17.086997  ...   
3             -329.868994  709.952915 -1334.911859     19.302189  ...   
4              875.686852  294.626779 -1279.075215     17.186408  ...   
5             -306.865102  402.216732 -1043.294178      5.131991  ...   

   z_contrib_NL      Net_Adv  $\mathcal{S}'_y$     dse_anom  dse_anom_Lag1  \
0      1.798309  -705.801441         -0.002151   110.929630     119.192018   
1     19.475541  -936.367250          0.000837   825.353184    2619.605998   
2      6.822952  -752.598533          0.002141  -171.628959     414.428641   
3      3.372212  -754.770886          0.005019   793.372485    1680.129163   
4      3.198356 -1015.545108         -0.003942   993.028169    1703.129178   
5     13.844999  -832.042123          0.004367  2741.316962    4043.701789   

       $u'$      $v'$      $w'$  $\mathcal{S}'_x$  $\mathcal{S}'_z$  
0  1.781251 -0.590410 -0.005415          0.001766         -0.232946  
1  1.062119  4.238345  0.001237          0.003351         -0.282281  
2 -0.065348  2.632642 -0.001481          0.001637          0.047313  
3 -2.183205  2.395116 -0.002121          0.000908         -0.080869  
4  3.530700 -5.572218 -0.004012         -0.002100         -0.045051  
5 -1.836591  3.690447  0.003416          0.000602         -0.282537  

[6 rows x 21 columns]

In [60]:
print(dir_out)

for file in files:
    
    print(file)
    
    print("out of", pd.read_csv(file, parse_dates=['date']).shape[0], "nc files,")
    
    existing_nc_lst = [
        s for s in os.listdir(dir_out) if 
        starts_with_substring_and_number(s, file.replace('.csv', '')+'_')
        and s.endswith('_2Dave.nc')
    ]
    
    print(len(existing_nc_lst), 'files exist')
    
#     [os.remove(dir_out + existing_nc_lst[i]) for i in range(len(existing_nc_lst))]
    
    existing_nc_lst = [
        s for s in os.listdir(dir_out) if 
        starts_with_substring_and_number(s, file.replace('.csv', '')+'_')
        and s.endswith('_2Dave.nc')
    ]
    print(len(existing_nc_lst), 'files exist')
#     print(existing_nc_lst)


/home/data/lab_hardik/heatwaves/ERA5/analyses/phase_relations/data/
Apr_posbg_decay_nl2_yNL_v2.csv
out of 6 nc files,
6 files exist
6 files exist


In [52]:
import read_data_DSE_Flux_Trees_1980_2022
from read_data_DSE_Flux_Trees_1980_2022 import *

In [48]:
# df_2010 = \
# df_t1.loc[df_t1.year == 2010]

In [54]:
for i in range(0,len(files)):
    for two_day_averaging in [True]:
        
        print(i)
        file = files[i]
        print(file)
        print('2Daveraging', two_day_averaging)

        df = pd.read_csv(file, parse_dates=['date'])

        desired_nc_lst = [
            file.replace('.csv','') + '_' + str(df.date[j].date()).replace('-','_') 
            + '_2Dave.nc' # new add
            for j in range(len(df.date))
        ]
        print(len(desired_nc_lst), 'files desired')

        existing_nc_lst = [
            s for s in os.listdir(dir_out) if 
            starts_with_substring_and_number(s, file.replace('.csv', '')+'_') 
            and s.endswith('_2Dave.nc') # new add
        ]
        print(len(existing_nc_lst), 'files exist')
        
#         break

        #    skip iter if files exist 
        if set(existing_nc_lst) == set(desired_nc_lst):
            print('index', i, 'already has all nc files in data folder')
            continue

#         if len(existing_nc_lst) > len(desired_nc_lst):
#             nc_to_rmv_lst = [s for s in existing_nc_lst if s not in desired_nc_lst]
#             for nc in nc_to_rmv_lst:
#                 print('removing files', nc)
#                 os.remove(dir_out + nc)
#                 existing_nc_lst.remove(nc)

#         desried_nc_updt = [s for s in desired_nc_lst if s not in existing_nc_lst]
#         print('len(desried_nc_updt)', len(desried_nc_updt))

        if 'Net_Adv' not in df.columns:
            df['Net_Adv'] = df['adv_recon_2Dave'].copy()

        flux_dts0 = df.date.to_list()
        print(len(flux_dts0), 'dates in original list')
#         print(len(existing_nc_lst), 'nc files available')

#         flux_dts = [
#             flux_dts0[i] for i in range(len(flux_dts0)) 
#             if file.replace('.csv','') + '_' + str(flux_dts0[i].date()).replace('-','_') + '.nc' 
#             in desried_nc_updt    
#         ]

        flux_dts = flux_dts0

        if len(flux_dts)==0:
            print('nothing to be written')
            continue

        print(len(flux_dts), 'dates to be written for', file)

        read_files_comp(dates=flux_dts, sample = np.nan, two_day_averaging = two_day_averaging)

        add_anoms()

        gc.collect()
        gc.collect()
        
        ds_brnch, ds_brnch2 = merge_branch_data(two_day_averaging=two_day_averaging)
        print(len(ds_brnch2.date), 'dates to be written for', file)

        for j in range(len(ds_brnch2.date)):
            print('i=', j)
            print(ds_brnch2.date.data[j])
            if two_day_averaging == False:
                file_out_str = file.replace('.csv','') + '_' + str(ds_brnch2.date.dt.date.data[j]).replace('-','_') + '.nc'
            else:
                file_out_str = file.replace('.csv','') + '_' + str(ds_brnch2.date.dt.date.data[j]).replace('-','_') + '_2Dave.nc'

        #         if file_out_str in [s for s in os.listdir(dir_out) if s.startswith(file.replace('.csv',''))]:
        #             continue

            ## In case of 2D averaged ds, only dse_anom_Lag1 is not 2D aved;  everything else is 2D aved
            with ProgressBar():
                ds_out = ds_brnch2.isel(date=j).drop(['number','step','strftime','dates_roll_clmt'])\
                    [['u','v','u_anom_10D','v_anom_10D','z_anom_10D','dse_anom', 'dse_anom_Lag1']].compute()

            # Check for NaN values
            has_nan = ds_out.isnull().any()
            print("Contains NaN values:")
            print(has_nan)
            
            if has_nan == False:
                print('writing', file_out_str)
            
                if file_out_str in os.listdir(dir_out):
                    os.remove(dir_out + file_out_str)
                    
                write_nc(
                    ds = ds_out, 
                    dir_out = dir_out,
                    file_out = file_out_str
                )

            print(len(ds_brnch2.date), 'dates have been written for', file)

            #     del ds_brnch, ds_z_comp, ds_t_comp, ds_v_comp, ds_u_comp
            gc.collect()
            gc.collect()

0
Apr_posbg_decay_nlsat_yNL_v2.csv
2Daveraging True
9 files desired
0 files exist
9 dates in original list
9 dates to be written for Apr_posbg_decay_nlsat_yNL_v2.csv
sample nan
sample == np.nan
len(brnch_dates) 9
len(brnch_dates2) 18
(3416, 2)
6 dates bw 1980 and 1994
12 dates bw 1995 and 2022
(10, 2)
i= 0
era5_geopotential_2008_4_14.nc
i= 1
era5_geopotential_2008_4_15.nc
i= 2
era5_geopotential_2016_4_17.nc
i= 3
era5_geopotential_2016_4_18.nc
i= 4
era5_geopotential_2016_4_19.nc
i= 5
era5_geopotential_2016_4_20.nc
i= 6
era5_geopotential_2019_4_29.nc
i= 7
era5_geopotential_2019_4_30.nc
i= 8
era5_geopotential_2021_4_5.nc
i= 9
era5_geopotential_2021_4_6.nc
ds w/ z dates b/w 95 and 22 is ready
dates_1980_1994 [numpy.datetime64('1980-04-11T00:00:00.000000000'), numpy.datetime64('1988-04-04T00:00:00.000000000'), numpy.datetime64('1991-04-21T00:00:00.000000000'), numpy.datetime64('1980-04-12T00:00:00.000000000'), numpy.datetime64('1988-04-05T00:00:00.000000000'), numpy.datetime64('1991-04-22T0

[########################################] | 100% Completed | 205.88 ms
Contains NaN values:
<xarray.Dataset>
Dimensions:        ()
Coordinates:
    date           datetime64[ns] 2019-04-30
Data variables:
    u              bool False
    v              bool False
    u_anom_10D     bool False
    v_anom_10D     bool False
    z_anom_10D     bool False
    dse_anom       bool False
    dse_anom_Lag1  bool False
writing Apr_posbg_decay_nlsat_yNL_v2_2019_04_30_2Dave.nc
9 dates have been written for Apr_posbg_decay_nlsat_yNL_v2.csv
i= 4
2016-04-18T00:00:00.000000000
[########################################] | 100% Completed | 307.91 ms
Contains NaN values:
<xarray.Dataset>
Dimensions:        ()
Coordinates:
    date           datetime64[ns] 2016-04-18
Data variables:
    u              bool False
    v              bool False
    u_anom_10D     bool False
    v_anom_10D     bool False
    z_anom_10D     bool False
    dse_anom       bool False
    dse_anom_Lag1  bool False
writing Apr_p