In [1]:
import os, xarray as xr, numpy as np, pandas as pd, dask, random, netCDF4
import cartopy.crs as ccrs, matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable

from datetime import datetime as dt, timedelta
import datetime, time

import importlib
import matplotlib.patches as mpatches
import gc
from matplotlib.gridspec import GridSpec
dask.config.set({"array.slicing.split_large_chunks": False})
import sys
sys.path.insert(1, '/home/data/lab_hardik/udf/')

import h5netcdf

ERROR 1: PROJ: proj_create_from_database: Open of /home/lab_hardik/my_conda/share/proj failed


In [2]:
import composite_funcs
import grad_funcs
importlib.reload(composite_funcs)
from composite_funcs import *
from grad_funcs import *

[30. 60. 90.]
[10. 30. 50.]
$\mathregular{\mathcal{S}'_{x}}$
["$u'$", "$v'$", "$w'$", "$\\mathcal{S}'_x$", "$\\mathcal{S}'_y$", "$\\mathcal{S}'_z$", '${u̅}$', '${v̅}$', '${w̅}$', '$\\mathcal{S}̅_x$', '$\\mathcal{S}̅_y$', '$\\mathcal{S}̅_z$']
dict_values(["$u'$$\\mathcal{S}'_x$", "$v'$$\\mathcal{S}'_y$", "$w'$$\\mathcal{S}'_z$", "$u'$$\\mathcal{S}̅_x$", "$v'$$\\mathcal{S}̅_y$", "$w'$$\\mathcal{S}̅_z$", "${u̅}$$\\mathcal{S}'_x$", "${v̅}$$\\mathcal{S}'_y$", "${w̅}$$\\mathcal{S}'_z$", '${u̅}$$\\mathcal{S}̅_x$', '${v̅}$$\\mathcal{S}̅_y$', '${w̅}$$\\mathcal{S}̅_z$'])
["$v'$$\\mathcal{S}̅_y$", "$w'$$\\mathcal{S}̅_z$", "${u̅}$$\\mathcal{S}'_x$"]
["$u'$$\\mathcal{S}'_x$", "$v'$$\\mathcal{S}'_y$", "$w'$$\\mathcal{S}'_z$"]
['${u̅}$$\\mathcal{S}̅_x$', '${v̅}$$\\mathcal{S}̅_y$', '${w̅}$$\\mathcal{S}̅_z$']
["$u'$$\\mathcal{S}̅_x$", "${v̅}$$\\mathcal{S}'_y$", "${w̅}$$\\mathcal{S}'_z$"]
[30. 60. 90.]
[10. 30. 50.]


In [3]:
# tst = xr.open_dataset('/home/data/lab_hardik/data/ERA5/climatology/t_3D/dly_clmtlgy_stdPlevs_prmnsn_temperature_1980_2022_wFeb.nc')
# tst.close()

importlib.reload(composite_funcs)
from composite_funcs import *

[30. 60. 90.]
[10. 30. 50.]


In [4]:

prepare_files(variable='u') # 1980 to 2022
prepare_files(variable='v') # 1980 to 2022
prepare_files(variable='t') # 1980 to 2022
prepare_files(variable='z') # 1995 to 2022


5246
['era5_u_component_of_wind_1980_3_1.nc', 'era5_u_component_of_wind_1980_3_2.nc', 'era5_u_component_of_wind_1980_3_3.nc', 'era5_u_component_of_wind_1980_3_4.nc', 'era5_u_component_of_wind_1980_3_5.nc', 'era5_u_component_of_wind_1980_3_6.nc']
5246
['era5_v_component_of_wind_1980_3_1.nc', 'era5_v_component_of_wind_1980_3_2.nc', 'era5_v_component_of_wind_1980_3_3.nc', 'era5_v_component_of_wind_1980_3_4.nc', 'era5_v_component_of_wind_1980_3_5.nc', 'era5_v_component_of_wind_1980_3_6.nc']
5246
['era5_temperature_1980_3_1.nc', 'era5_temperature_1980_3_2.nc', 'era5_temperature_1980_3_3.nc', 'era5_temperature_1980_3_4.nc', 'era5_temperature_1980_3_5.nc', 'era5_temperature_1980_3_6.nc']
3416
['era5_geopotential_1995_3_1.nc', 'era5_geopotential_1995_3_2.nc', 'era5_geopotential_1995_3_3.nc', 'era5_geopotential_1995_3_4.nc', 'era5_geopotential_1995_3_5.nc', 'era5_geopotential_1995_3_6.nc']


In [5]:
ds_z_1980_1994 = prepare_z_ds(year_min = 1980, year_max = 1994)

['era5/.zgroup', 'era5/.zmetadata', 'era5/era5']


/home/lab_hardik/my_conda/lib/python3.9/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
/home/lab_hardik/my_conda/lib/python3.9/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
/home/lab_hardik/my_conda/lib/python3.9/site-packages/paramiko/transport.py:243: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
/home/data/lab_hardik/udf/composite_funcs.py:62: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanose

In [6]:
ds_z_1980_1994 = \
ds_z_1980_1994.sel(isobaricInhPa = slice(600,900))
# .rechunk({'isobaricInhPa':1, 'longitude':720})

In [7]:
dat_dir = '/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files/'
# files = [s for s in os.listdir(dat_dir) if 'Apr' in s]
# # files.sort(key = os.path.getctime)
# files

In [8]:
os.chdir(dat_dir)

In [9]:
# df_ampfl_nl = pd.read_csv('Apr_Amplf_NonLin_DSEFlx.csv', 
#                                 parse_dates=['date'])

# df_ampfl_lin = pd.read_csv('Apr_Amplf_Lin_DSEFlx.csv', 
#                                 parse_dates=['date'])

# df_ampfl_lin2 = pd.read_csv('Apr_Amplf_Lin_ZonalDSEFlx.csv', 
#                                 parse_dates=['date'])



In [10]:
# df_ntrl = pd.read_csv('Apr_tercile_based_neutral_dseflx_dts.csv', 
#                                 parse_dates=['date'])

# df_growth_nl = pd.read_csv('Apr_Growth_NL_Lag1Flx_5Cat.csv', 
#                                 parse_dates=['date'])

# df_growth_lin = pd.read_csv('Apr_Growth_Lin_Lag1Flx_5Cat.csv', 
#                                 parse_dates=['date'])


In [11]:
# df = df_ntrl.copy()
# df = df_growth_nl.copy()
# df = df_growth_lin.copy()

# df = df_ampfl_lin.copy()
# df = df_ampfl_lin2.copy()
# df = df_ampfl_nl.copy()
# df

# Some lag1 plotting for no clear reason

In [12]:
# flux_dts = (df.date - pd.Timedelta('1 day')).to_list()
# ds_brnch = df_prep(dates=flux_dts).copy()


In [13]:
# global fig, ax

# dates = ds_brnch.date.data
# num_plots = 10 if len(dates)>=10 else len(dates)

# fig, ax = plt.subplots(int(np.ceil(num_plots/2)),2, figsize=(16,20), 
#                        sharey=True, subplot_kw={'projection': ccrs.PlateCarree()})

# for i in range(len(dates)):
#     r = bicol_panel_rownum(i)
#     c = bicol_panel_colnum(i)
#     print(r)
#     print(c)

# #     tot_flx = df.adv_recon_.iloc[i].round(0)
#     tot_flx = df.loc[df.date == (dates[i] + pd.Timedelta('1 day')),'adv_recon_Lag1'].values[0].round(0)
    
#     da_plt = ds_brnch['dse_anom'].sel(date = dates[i]).compute()#.mean(['date']).compute()
#     da_cont = ds_brnch['z_anom_10D'].sel(date = dates[i]).compute()#.mean(['date']).compute()
#     da_u = (ds_brnch['u_anom_10D']).sel(date = dates[i]).compute()#.mean(['date']).compute()
#     da_v = (ds_brnch['v_anom_10D']).sel(date = dates[i]).compute()#.mean(['date']).compute()
#     # da_u = ds_brnch['adv_flx_x'].mean(['date']).compute()
#     # da_v = ds_brnch['adv_flx_y'].mean(['date']).compute()

#     # vmin = np.nan; vmax=np.nan
#     inner_plot_composite(
#         da_plt = da_plt, da_cont = da_cont, da_u = da_u, da_v =da_v, xmin=0, xmax=120, ymin=10, ymax=65, 
#         cont_divisions=20, coarsen_pts=8,
#         t_type = 'dse_anom',scale_quiv= 70, 
#         i = r, j = c, ax=ax[r,c], 
#         title_str = 'dse_flx = {}, date = {}'.format(tot_flx, str(dates[i]))
#         )
# plt.tight_layout()


In [14]:
# dts_0 = pd.read_csv(dat_dir + 'Dates_Apr_w\'_v\'_mismatch.csv', parse_dates=['date'])
# dts_1 = pd.read_csv('Dates_Apr_largePosTprim_smallNonLin.csv', parse_dates=['date'])
# dts_2 = pd.read_csv('Dates_Apr_largePosTprim_LargePosT3.csv', parse_dates=['date'])


In [15]:
dts_posExt_vs = pd.read_csv(dat_dir + 'Apr_posExt_vs_path.csv', parse_dates=['date'])
dts_posExt_us = pd.read_csv(dat_dir + 'Apr_posExt_us_path.csv', parse_dates=['date'])


In [16]:
# Dates_Mar_extNegD0Flx_PosLag1T2m = pd.read_csv('Dates_Mar_extNegD0Flx_PosLag1T2m.csv', parse_dates=['date'])
# Dates_Mar_extNegD0Flx_NeutLag1T2m = pd.read_csv('Dates_Mar_extNegD0Flx_NeutLag1T2m.csv', parse_dates=['date'])
# Dates_Mar_extNegD0Flx_NegLag1T2m = pd.read_csv('Dates_Mar_extNegD0Flx_NegLag1T2m.csv', parse_dates=['date'])


In [17]:
# df = dts_1.copy()
# df = dts_2.copy()
# df = dts_3.copy()
# brnch_dates = dts_0.date

# df = dts_0.copy()
# df = Dates_Mar_extNegD0Flx_PosLag1T2m.copy()
# df = Dates_Mar_extNegD0Flx_NeutLag1T2m.copy()
# df = Dates_Mar_extNegD0Flx_NegLag1T2m.copy()

# df = pd.read_csv(dat_dir + 'Dates_Apr_largePosTprim_LargePosT3.csv', parse_dates=['date'])
# df = dts_posExt_us.copy()
# df = dts_posExt_vs.copy()
# df = pd.read_csv(dat_dir + 'Apr_negExt_vs_path.csv', parse_dates=['date'])

# df = pd.read_csv(dat_dir + 'Apr_negExt_us_path.csv', parse_dates=['date'])
# df = df.loc[df['v\'_s\''] < 0]

# df = pd.read_csv(dat_dir + 'Apr_neg_amplf_quad_anal.csv', parse_dates=['date'])
# df = pd.read_csv(dat_dir + 'Apr_neg_decay_quad_anal.csv', parse_dates=['date'])




# df_ampfl_nl_x_contrib = pd.read_csv('Apr_pos_ampfl_x_contrib.csv', parse_dates=['date'])
# df_ampfl_nl_y_contrib = pd.read_csv('Apr_pos_ampfl_y_contrib.csv', parse_dates=['date'])

# df_neg_decay_nl_z_contrib = pd.read_csv('Apr_neg_decay_z_contrib.csv', parse_dates=['date'])

# df_pos_decay_nl_y_contrib = pd.read_csv('Apr_pos_decay_y_contrib.csv', parse_dates=['date'])
# df_pos_decay_nl_x_contrib = pd.read_csv('Apr_pos_decay_x_contrib.csv', parse_dates=['date'])


# df = df_ampfl_nl_x_contrib
# df = df_ampfl_nl_y_contrib
# df = df_neg_decay_nl_z_contrib
# 
# df = df_pos_decay_nl_y_contrib
# df = df_pos_decay_nl_x_contrib


# df = pd.read_csv('Apr_neg_v\'_large_xymain_small_zmain.csv', parse_dates = ['date'])
df = pd.read_csv('Apr_pos_v\'_large_xymain_small_zmain.csv', parse_dates = ['date'])


In [18]:
import variables
from variables import *

In [19]:
# 'ds_z_comp' in globals()

[s for s in dir() if 'ds_z_comp' in s]

[]

In [20]:
dat_dir

'/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files/'

In [21]:
def compute_M(ds = xr.Dataset()): #ds_brnch_path1
    
    R = 287
    Rearth = 6378*10**3
    steps_x = 4*10
    del_lambda = 0.25*np.pi/180
    del_phi = 0.25*np.pi/180

    ds = compute_zdiff_fields(ds)
    ds['density'] = (ds['isobaricInhPa']*100)/(287*ds['t'])

    Axy_2 = Rearth**2*del_lambda*(
        np.sin((Rlat.latitude + 0.25)*np.pi/180) - np.sin(Rlat.latitude*np.pi/180)
    )
    M = (Axy_2*ds['z_diff_down']/g*.5*(ds['density'] + ds['density'].shift(isobaricInhPa=-1)))\
    .sel(latitude=slice(24,30.75), longitude=slice(68,77.75))
    
    return M


In [22]:
def plot_samples(ds, save_str = ''):
#     global fig, ax
    # num_plots = 10 if df.shape[0]>=10 else df.shape[0]
    # num_plots = 10 if len(ds.date)>=10 else len(ds.date)

    # num_plots = int(np.ceil(len(ds.date)/2)*2)

    num_plots = len(ds.date)

    nrow = int(np.ceil(num_plots/2))

    fig, ax = plt.subplots(
        nrow,2, figsize=(16, nrow*4), sharey=True, subplot_kw={'projection': ccrs.PlateCarree()}
    )

    for i in range(num_plots):
        r = bicol_panel_rownum(i)
        c = bicol_panel_colnum(i)
        print('rowunm',r)
        print('colnum',c)

        tot_flx = df.Net_Adv.iloc[i].round(0)
        dse_anom = df.dse_anom.iloc[i].round(0)

        da_plt = ds[dse_var].isel(date = i)#.mean(['date'])#.compute()
        da_cont = ds[z_var].isel(date = i)#.mean(['date'])#.compute()
        da_u = (ds[u_var]).isel(date = i)#.mean(['date'])#.compute()
        da_v = (ds[v_var]).isel(date = i)#.mean(['date'])#.compute()
        # da_u = ds['adv_flx_x'].mean(['date']).compute()
        # da_v = ds['adv_flx_y'].mean(['date']).compute()

        # vmin = np.nan; vmax=np.nan
        inner_plot_composite(
            da_plt = da_plt, da_cont = da_cont, da_u = da_u, da_v = da_v, xmin=0, xmax=120, ymin=10, ymax=65, 
            cont_divisions=20, coarsen_pts=8,
            t_type = 'dse_anom',scale_quiv= 70, 
            i = r, j = c, ax=ax[r,c], 
            title_str = 'dse_anom = {}, dse_flx = {}, date = {}'.format(dse_anom, tot_flx, str(df.date.iloc[i].date()))
            )
    plt.tight_layout()
    
    if save_str != '':
        plt.savefig('/home/data/lab_hardik/heatwaves/ERA5/analyses/phase_relations/{}'.format(save_str))


In [23]:
dir_out = '/home/data/lab_hardik/heatwaves/ERA5/analyses/phase_relations/data/'

In [24]:
sample=np.nan

In [25]:
sample != sample

True

In [26]:
import re 
def starts_with_substring_and_number(s, substring): 
    pattern = rf"^{re.escape(substring)}\d+" 
    return re.match(pattern, s) is not None 
# Example usage 
string = "prefix12345" 
substring = "prefix" 
result = starts_with_substring_and_number(string, substring) 
print(result) 
# Output: True


True


In [27]:
def read_files_comp(dates = list(), sample=np.nan, two_day_averaging = True):
    global ds_z_comp, ds_v_comp, ds_u_comp, ds_t_comp, brnch_dates, brnch_dates2
#     brnch_dates = df.date.sample(10 if df.shape[0] >= 10 else df.shape[0])
    print('sample', sample)

    if sample != sample: 
        print('sample == np.nan')
        brnch_dates = dates
    else: 
        brnch_dates = random.sample(dates, sample if df.shape[0] >= sample else df.shape[0])

    print('len(brnch_dates)', len(brnch_dates))

    if two_day_averaging == True: 
        brnch_dates2 = ([s - timedelta(days=1) for s in brnch_dates] + brnch_dates)
        print('len(brnch_dates2)', len(brnch_dates2))
    else: 
        brnch_dates2 = brnch_dates
    
    press = slice(900,600)

    ds_z_comp = filt_comp_files(
        variable='z', dates = brnch_dates2, press=press, 
        ds_z_1980_1994 = ds_z_1980_1994.sortby('isobaricInhPa', ascending=False), 
        ymin=10, ymax=60, xmin=0, xmax=120
    )
    
    ds_v_comp = filt_comp_files(variable='v', dates = brnch_dates2, press= press, ymin=10, ymax=60, xmin=0, xmax=120)
    ds_u_comp = filt_comp_files(variable='u', dates = brnch_dates2, press=press, ymin=10, ymax=60, xmin=0, xmax=120)
    ds_t_comp = filt_comp_files(variable='t', dates = brnch_dates2, press=press, ymin=10, ymax=60, xmin=0, xmax=120)
    

In [28]:
# brnch_dates

In [29]:
# brnch_dates2

In [30]:
def add_anoms():
    global ds_z_comp, ds_v_comp, ds_u_comp, ds_t_comp
    
    press = slice(900,600)
    ds_z_comp = create_anoms(variable='z', press=press, ds=ds_z_comp, clmt_file_map = rolling_clmt_file_map)
    ds_t_comp = create_anoms(variable='t', press=press, ds=ds_t_comp, clmt_file_map = rolling_clmt_file_map)
    ds_u_comp = create_anoms(variable='u', press=press, ds=ds_u_comp, clmt_file_map = rolling_clmt_file_map)
    ds_v_comp = create_anoms(variable='v', press=press, ds=ds_v_comp, clmt_file_map = rolling_clmt_file_map)

    ds_t_comp['t_clmt'] = ds_t_comp['t'] - ds_t_comp['t_anom_10D']
    ds_z_comp['z_clmt'] = ds_z_comp['z'] - ds_z_comp['z_anom_10D']

    ds_u_comp['u_clmt'] = ds_u_comp['u'] - ds_u_comp['u_anom_10D']
    ds_v_comp['v_clmt'] = ds_v_comp['v'] - ds_v_comp['v_anom_10D']

In [31]:
def merge_branch_data(two_day_averaging = True):
    ymin=10
    ymax=60
    xmin=0
    xmax=120
    
    global ds_v_comp, ds_u_comp, ds_z_comp, ds_t_comp, ds_brnch_path1, ds_brnch, ds_brnch2, da_dse_anom_Lag1
    
    ds_brnch_path1 = xr.combine_by_coords(
        [ds_v_comp, ds_u_comp, ds_z_comp, ds_t_comp], 
        join='inner', combine_attrs='drop_conflicts'
    )\
    .sel(latitude=slice(ymax,ymin), longitude=slice(xmin,xmax)).chunk({'latitude':241,'longitude':481})

    ds_brnch_path1['density'] = (ds_brnch_path1['isobaricInhPa']*100)/(287*ds_brnch_path1['t'])
    
    gc.collect()

#     Rlat = Rlat_fn(ds = ds_brnch_path1)
#     M = compute_M(ds = ds_brnch_path1)

    ds_brnch = ds_brnch_path1.weighted(ds_brnch_path1['density'])\
    .mean('isobaricInhPa').sortby(['latitude','longitude','date'])
    
#     for variable in list(ds_brnch.data_vars):
#         print(variable)
#         ds_brnch[variable] = vert_MassAve_qty(
#             M = M, 
#             qty = ds_brnch[variable], 
#             p_low=600, p_high=900
#         ).compute()
    
    print('ds_brnch.dims', ds_brnch.dims)

    ds_brnch['dse'] = 1005*ds_brnch['t'] + ds_brnch['z']
    ds_brnch['dse_anom'] = 1005*ds_brnch['t_anom_10D'] + ds_brnch['z_anom_10D']
    ds_brnch['dse_clmt'] = 1005*ds_brnch['t_clmt'] + ds_brnch['z_clmt']
    ds_brnch['dse_anom_Lag1'] = ds_brnch['dse_anom'].shift(date=1)
    
    da_dse_anom_Lag1 = ds_brnch['dse_anom_Lag1'].sel(date = brnch_dates)

    if two_day_averaging == True:
        ds_brnch = ds_brnch.sortby('date')
        ds_brnch2 = 0.5*(ds_brnch + ds_brnch.shift(date = 1))

        ds_brnch2 = xr.merge(
            [
                ds_brnch2[[s for s in list(ds_brnch2.data_vars) if 'Lag1' not in s]].sel(date = brnch_dates), 
                da_dse_anom_Lag1, 

            ])

        print('len(ds_brnch.date)',len(ds_brnch.date))
        print('len(ds_brnch2.date)',len(ds_brnch2.date))
        
#         da_z_tst0 = client.scatter(ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[0]))
#         da_z_tst1 = client.scatter(ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]))
#         da_z_tst2 = client.scatter(ds_brnch2['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]))

#         def myfunc(dask_array):
#             return dask_array.compute()

#         future0 = client.submit(myfunc, da_z_tst0)
#         a0 = client.gather(future0)

        a0 = ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[0]).values
        a1 = ds_brnch['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]).values
        a2 = ds_brnch2['z_anom_10D'].isel(latitude=20, longitude=20).sel(date = ds_brnch.date[1]).values
        
#         future1 = client.submit(myfunc, da_z_tst1)
#         a1 = client.gather(future1)# ds_brnch['z_anom_10D'].sel(date = ds_brnch.date[1])[20,20].values
        
#         future2 = client.submit(myfunc, da_z_tst2)
#         a2 = client.gather(future2) #ds_brnch2['z_anom_10D'].sel(date = ds_brnch.date[1])[20,20].values

        print(0.5*(a0+a1))
        print(a2)

        if np.round(0.5*(a0+a1),3) != np.round(a2,3):
            return 'incorrect 2D ave'
    else:
        ds_brnch2 = ds_brnch

    print(ds_brnch2.dims)
    print(ds_brnch2.data_vars)
    
#     del ds_v_comp, ds_u_comp, ds_z_comp, ds_t_comp
    gc.collect()
    gc.collect()
    
    return ds_brnch, ds_brnch2

def write_nc(ds, dir_out = dir_out, file_out = str):
    ds.to_netcdf(dir_out + file_out)

In [32]:
# with ProgressBar():
#     da_tst = ds_z_comp.sel(isobaricInhPa=600, latitude=25, longitude=75).compute()
    

In [33]:
# da_tst

In [34]:
gc.collect()

0

In [35]:
importlib.reload(grad_funcs)
from grad_funcs import *

importlib.reload(composite_funcs)
from composite_funcs import *


[30. 60. 90.]
[10. 30. 50.]


In [36]:
dat_dir

'/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files/'

In [37]:

# files = [s for s in os.listdir(dat_dir) if 'Apr_posbg_decay_nl_' in s]
# files = [s for s in os.listdir(dat_dir) if 'Apr_posbg_' in s]
# files = [s for s in os.listdir(dat_dir) if 'Apr_posbg_amplif_nlsat_' in s]
# files = [s for s in os.listdir(dat_dir) if 'Apr_posbg_amplif_full_yNL_' in s]
# files = [s for s in os.listdir(dat_dir) if 'Apr_posbg_decay_ql' in s]
# files = [s for s in os.listdir(dat_dir) if '_w_' in s and s.endswith('v.csv')]
# files = [s for s in os.listdir(dat_dir) if s.endswith('ws_small.csv')]
# files = [s for s in os.listdir(dat_dir) if s.startswith('prim_lrg') and s.endswith('small_ws.csv')]
# files = [s for s in os.listdir(dat_dir) if ('pos_ext_cycle' in s) and s.endswith('csv')]

# files = [s for s in os.listdir(dat_dir) if (s.startswith('prim_r1') or s.startswith('prim_r3')) and s.endswith('bg.csv') and 'us_ip_vs' not in s]

# files = [s for s in os.listdir(dat_dir) if (s.startswith('prim_r2_1') or s.startswith('prim_r4_1')) and s.endswith('bg.csv')]

# files = [s for s in os.listdir(dat_dir) if s.startswith('Apr_posbg') or s.startswith('Apr_negbg') and 'bg1' not in s]

# files = [s for s in os.listdir(dat_dir) if s.startswith('Apr_neg') and 'v2' in s]
# files = [s for s in os.listdir(dat_dir) if s.startswith('Mar') and 'v2' in s]
# files = [s for s in os.listdir(dat_dir) if 'lrg_ws_us_sml_vs' in s and 'Apr_' in s]
# files = [s for s in os.listdir(dat_dir) if (('prim_r' in s) and ('bg' in s)) and 'Apr_' in s]

# files = [s for s in os.listdir(dat_dir) if s.startswith('Apr_pos') and 'v2' in s 
#          and 'nl1' not in s and 'nl2' not in s
#         and 'amplif_nl_xNL' not in s # this was from an old run
#          and 'posbg2_decay_nl_xNL' not in s # posbg2 is included in posbg
#         ]

mar_csvs = [
    
    'Mar_posbg_amplif_nlsat_xNL_v2.csv', 
    'Mar_posbg_amplif_nlsat_yNL_v2.csv',
    
    'Mar_posbg_amplif_ql_xy_v2.csv',
    'Mar_posbg_amplif_nl_yNL_v2.csv', 

    'Mar_posbg_decay_ql_xy_v2.csv', 
    'Mar_posbg_decay_nl_yNL_v2.csv', 'Mar_posbg_decay_nl_xNL_v2.csv',
    'Mar_posbg2_decay_ql_xy_v2.csv', 'Mar_posbg2_decay_nl_xNL_v2.csv',
    
    'Mar_negbg_amplif_ql_xy_v2.csv', 'Mar_negbg2_amplif_ql_xy_v2.csv', 
    'Mar_negbg_decay_ql_xy_v2.csv', 'Mar_negbg2_decay_ql_xy_v2.csv', 'Mar_negbg2_decay_nl_zNL_v2.csv'
]
# files = [s for s in os.listdir(dat_dir) if s.startswith('Mar_posbg') or s.startswith('Mar_negbg')]

# files.sort(key = os.path.getctime)


files = [s for s in os.listdir(dat_dir) if s.startswith('Apr_negbg') and 'v2' in s 
         and 'nl1' not in s and 'nl2' not in s
        and 'amplif_nl_xNL' not in s # this was from an old run
         and 'posbg2_decay_nl_xNL' not in s # posbg2 is included in posbg
        ]

files_negbg_addn = ['Apr_negbg1_decay_ql_xy_z_v2.csv', 'Apr_negbg1_amplif_full_xNL_v2.csv']
files = files_negbg_addn
files.sort(key = lambda s: (s.split('_')[1], s.split('_')[2], s.split('_')[3]))
# print(files[:10])
print(len(files))

# [s for s in files if any(t in s for t in ['negbg_decay_full_', 'negbg_decay_ql'])]
files


2


['Apr_negbg1_amplif_full_xNL_v2.csv', 'Apr_negbg1_decay_ql_xy_z_v2.csv']

In [38]:
csvs_negbg = [
    'Apr_negbg_amplif_ql_xy_v2.csv', 'Apr_negbg_amplif_nlsat_yNL_v2.csv', 
    'Apr_negbg_decay_ql_xy_z_v2.csv', 'Apr_negbg_decay_ql_xy_v2.csv', 'Apr_negbg_decay_full_yzNL_v2.csv', 
    
    'Apr_negbg2_amplif_full_xyNL_v2.csv', 'Apr_negbg2_decay_nlsat_xNL_v2.csv', 
    'Apr_negbg2_decay_ql_xy_v2.csv', 'Apr_negbg2_decay_nl_xyz_v2.csv'
]


In [39]:
['Apr_posbg_decay_nl_yNL_v2.csv', 
'Apr_posbg_decay_nl_xNL_v2.csv', 
'Apr_posbg_decay_ql_xy_v2.csv']

['Apr_posbg_decay_nl_yNL_v2.csv',
 'Apr_posbg_decay_nl_xNL_v2.csv',
 'Apr_posbg_decay_ql_xy_v2.csv']

## New data prep section

In [40]:
importlib.reload(composite_funcs)
from composite_funcs import *

[30. 60. 90.]
[10. 30. 50.]


In [41]:
dir_out

'/home/data/lab_hardik/heatwaves/ERA5/analyses/phase_relations/data/'

In [42]:
# files = mar_csvs
os.getcwd()

'/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files'

In [43]:
files

['Apr_negbg1_amplif_full_xNL_v2.csv', 'Apr_negbg1_decay_ql_xy_z_v2.csv']

In [44]:

for file in files:
    print(file)
    print("out of", pd.read_csv(file, parse_dates=['date']).shape[0], "nc files,")
    existing_nc_lst = [
        s for s in os.listdir(dir_out) if 
        starts_with_substring_and_number(s, file.replace('.csv', '')+'_')
        and s.endswith('_2Dave.nc')
    ]
    print(len(existing_nc_lst), 'files exist')
#     print(existing_nc_lst)



Apr_negbg1_amplif_full_xNL_v2.csv
out of 9 nc files,
0 files exist
Apr_negbg1_decay_ql_xy_z_v2.csv
out of 12 nc files,
0 files exist


In [45]:
os.getcwd()

'/home/data/lab_hardik/heatwaves/ERA5/dtree_anoms/processed_files'

In [46]:
pd.read_csv("Apr_negbg1_amplif_full_xNL_v2.csv")

date  $u'$$\mathcal{S}'_x$  $v'$$\mathcal{S}'_y$  \
0  1983-04-07           -833.190608            233.867194   
1  1983-04-15          -1050.792805           1616.004213   
2  1983-04-16          -1288.332092           1609.974528   
3  1984-04-29           -159.712393           -284.605600   
4  1999-04-14          -1040.877082            312.969784   
5  2009-04-06           -780.050979             57.850885   
6  2009-04-23           -378.960706            -74.326895   
7  2016-04-23           -410.694355            -50.696500   
8  2020-04-18           -694.960771            220.392424   

   $w'$$\mathcal{S}'_z$  $v'$$\mathcal{S}̅_y$  $w'$$\mathcal{S}̅_z$  \
0             28.419602           1429.481348           -602.079633   
1          -1838.074368           1523.631210          -2571.175253   
2          -1118.978005           1687.970358          -1612.108999   
3             -2.921814           -337.555465            128.505462   
4              9.155459            471.456505           1166.817112   
5             14.062820           1197.414603            308.505021   
6           -256.063459           -182.515422            928.952186   
7            -23.312118           -204.197521            -65.408757   
8             41.647336            747.354904           -439.133529   

   ${u̅}$$\mathcal{S}'_x$       T_main       NL_sum  x_contrib_NL  \
0            -1073.510283  -246.108568  -570.903812     76.057307   
1            -1191.480200 -2239.024243 -1272.862960     23.325700   
2            -1629.901339 -1554.039980  -797.335569     32.069724   
3             -108.656794  -317.706797  -447.239807     35.710684   
4            -2090.193706  -451.920089  -718.751839     76.366494   
5            -1546.129949   -40.210325  -708.137275     91.559074   
6             -840.668642   -94.231878  -709.351061     53.423576   
7             -216.631643  -486.237921  -484.702973     84.731140   
8             -800.058548  -491.837173  -432.921011     72.618640   

   y_contrib_NL  z_contrib_NL      Net_Adv  $\mathcal{S}'_y$     dse_anom  \
0     21.348427      2.594266  -932.895572         -0.000728 -3738.919142   
1     35.872372     40.801928 -3877.573053         -0.003772 -7733.681307   
2     40.076188     27.854088 -2646.498907         -0.003523 -8707.517676   
3     63.636017      0.653299  -781.399654         -0.001599  -979.758974   
4     22.961794      0.671713 -1328.877034         -0.001349 -1636.042386   
5      6.790291      1.650634  -826.192110         -0.000511 -2005.224657   
6     10.478154     36.098270  -770.252092         -0.002091 -2128.087307   
7     10.459292      4.809568 -1052.826067         -0.003254 -1676.149587   
8     23.029499      4.351861 -1012.245921         -0.003835 -1695.763167   

   dse_anom_Lag1  
0   -2359.262567  
1   -6558.491829  
2   -7733.681307  
3    -283.089512  
4    -806.141209  
5    -307.026466  
6   -2012.931400  
7    -794.935048  
8   -1161.828369

In [47]:
importlib.reload(composite_funcs)
from composite_funcs import *

[30. 60. 90.]
[10. 30. 50.]


In [48]:
# from dask.distributed import Client, LocalCluster

# if 'client' in globals():
#     client.close()
#     cluster.close()

# # Create a cluster with memory limits
# cluster = LocalCluster(n_workers=6, threads_per_worker=4, memory_limit='16GB')
# client = Client(cluster)


In [49]:
# for i in [i for i in range(len(files)) if any(t in files[i] for t in ['negbg_decay_full_', 'negbg_decay_ql'])]:
for i in range(0,len(files)):
# for i in [1]:
    for two_day_averaging in [True]:
        
        print(i)
        file = files[i]
        print(file)
        print('2Daveraging', two_day_averaging)

        df = pd.read_csv(file, parse_dates=['date'])

        desired_nc_lst = [
            file.replace('.csv','') + '_' + str(df.date[j].date()).replace('-','_') 
            + '_2Dave.nc' # new add
            for j in range(len(df.date))
        ]
        print(len(desired_nc_lst), 'files desired')

        existing_nc_lst = [
            s for s in os.listdir(dir_out) if 
            starts_with_substring_and_number(s, file.replace('.csv', '')+'_') 
            and s.endswith('_2Dave.nc') # new add
        ]
        print(len(existing_nc_lst), 'files exist')
        
#         break

        #    skip iter if files exist 
#         if set(existing_nc_lst) == set(desired_nc_lst):
#             print('index', i, 'already has all nc files in data folder')
#             continue

#         if len(existing_nc_lst) > len(desired_nc_lst):
#             nc_to_rmv_lst = [s for s in existing_nc_lst if s not in desired_nc_lst]
#             for nc in nc_to_rmv_lst:
#                 print('removing files', nc)
#                 os.remove(dir_out + nc)
#                 existing_nc_lst.remove(nc)

#         desried_nc_updt = [s for s in desired_nc_lst if s not in existing_nc_lst]
#         print('len(desried_nc_updt)', len(desried_nc_updt))

        if 'Net_Adv' not in df.columns:
            df['Net_Adv'] = df['adv_recon_2Dave'].copy()

        flux_dts0 = df.date.to_list()
        print(len(flux_dts0), 'dates in original list')
#         print(len(existing_nc_lst), 'nc files available')

#         flux_dts = [
#             flux_dts0[i] for i in range(len(flux_dts0)) 
#             if file.replace('.csv','') + '_' + str(flux_dts0[i].date()).replace('-','_') + '.nc' 
#             in desried_nc_updt    
#         ]

        flux_dts = flux_dts0

        if len(flux_dts)==0:
            print('nothing to be written')
            continue

        print(len(flux_dts), 'dates to be written for', file)

        read_files_comp(dates=flux_dts, sample = np.nan, two_day_averaging = two_day_averaging)

        add_anoms()

        gc.collect()
        gc.collect()
        
        ds_brnch, ds_brnch2 = merge_branch_data(two_day_averaging=two_day_averaging)
        print(len(ds_brnch2.date), 'dates to be written for', file)

        for j in range(len(ds_brnch2.date)):
            print('i=', j)
            print(ds_brnch2.date.data[j])
            if two_day_averaging == False:
                file_out_str = file.replace('.csv','') + '_' + str(ds_brnch2.date.dt.date.data[j]).replace('-','_') + '.nc'
            else:
                file_out_str = file.replace('.csv','') + '_' + str(ds_brnch2.date.dt.date.data[j]).replace('-','_') + '_2Dave.nc'

        #         if file_out_str in [s for s in os.listdir(dir_out) if s.startswith(file.replace('.csv',''))]:
        #             continue

            ## In case of 2D averaged ds, only dse_anom_Lag1 is not 2D aved;  everything else is 2D aved
            with ProgressBar():
                ds_out = ds_brnch2.isel(date=j).drop(['number','step','strftime','dates_roll_clmt'])\
                    [['u','v','u_anom_10D','v_anom_10D','z_anom_10D','dse_anom', 'dse_anom_Lag1']].compute()

            # Check for NaN values
            has_nan = ds_out.isnull().any()
            print("Contains NaN values:")
            print(has_nan)
            
            if has_nan == False:
                print('writing', file_out_str)
            
                if file_out_str in os.listdir(dir_out):
                    os.remove(dir_out + file_out_str)
                    
                write_nc(
                    ds = ds_out, 
                    dir_out = dir_out,
                    file_out = file_out_str
                )

            #     del ds_brnch, ds_z_comp, ds_t_comp, ds_v_comp, ds_u_comp
            gc.collect()
            gc.collect()
        
        print(len(ds_brnch2.date), 'dates have been written for', file)



0
Apr_negbg1_amplif_full_xNL_v2.csv
2Daveraging True
9 files desired
0 files exist
9 dates in original list
9 dates to be written for Apr_negbg1_amplif_full_xNL_v2.csv
sample nan
sample == np.nan
len(brnch_dates) 9
len(brnch_dates2) 18
(3416, 2)
8 dates bw 1980 and 1994
10 dates bw 1995 and 2022
(10, 2)
i= 0
era5_geopotential_1999_4_13.nc
i= 1
era5_geopotential_1999_4_14.nc
i= 2
era5_geopotential_2009_4_5.nc
i= 3
era5_geopotential_2009_4_6.nc
i= 4
era5_geopotential_2009_4_22.nc
i= 5
era5_geopotential_2009_4_23.nc
i= 6
era5_geopotential_2016_4_22.nc
i= 7
era5_geopotential_2016_4_23.nc
i= 8
era5_geopotential_2020_4_17.nc
i= 9
era5_geopotential_2020_4_18.nc
ds w/ z dates b/w 95 and 22 is ready
dates_1980_1994 [numpy.datetime64('1983-04-06T00:00:00.000000000'), numpy.datetime64('1983-04-14T00:00:00.000000000'), numpy.datetime64('1983-04-15T00:00:00.000000000'), numpy.datetime64('1984-04-28T00:00:00.000000000'), numpy.datetime64('1983-04-07T00:00:00.000000000'), numpy.datetime64('1983-04-15

i= 3
1984-04-29T00:00:00.000000000
[########################################] | 100% Completed | 1.04 sms
Contains NaN values:
<xarray.Dataset>
Dimensions:        ()
Coordinates:
    date           datetime64[ns] 1984-04-29
Data variables:
    u              bool False
    v              bool False
    u_anom_10D     bool False
    v_anom_10D     bool False
    z_anom_10D     bool False
    dse_anom       bool False
    dse_anom_Lag1  bool False
writing Apr_negbg1_amplif_full_xNL_v2_1984_04_29_2Dave.nc
i= 4
1999-04-14T00:00:00.000000000
[########################################] | 100% Completed | 580.35 ms
Contains NaN values:
<xarray.Dataset>
Dimensions:        ()
Coordinates:
    date           datetime64[ns] 1999-04-14
Data variables:
    u              bool False
    v              bool False
    u_anom_10D     bool False
    v_anom_10D     bool False
    z_anom_10D     bool False
    dse_anom       bool False
    dse_anom_Lag1  bool False
writing Apr_negbg1_amplif_full_xNL_v2_199

['t_dly_clmt', 't_dly_clmt_10D_roll']
('clmt_roll_strftime', 'isobaricInhPa', 'latitude', 'longitude')
['u_dly_clmt', 'u_dly_clmt_10D_roll']
('clmt_roll_strftime', 'isobaricInhPa', 'latitude', 'longitude')
['v_dly_clmt', 'v_dly_clmt_10D_roll']
('clmt_roll_strftime', 'isobaricInhPa', 'latitude', 'longitude')
ds_brnch.dims Frozen({'latitude': 201, 'longitude': 481, 'date': 22})
len(ds_brnch.date) 22
len(ds_brnch2.date) 12
-117.44668539214383
-117.44668539214383
Frozen({'date': 12, 'latitude': 201, 'longitude': 481})
Data variables:
    t              (date, latitude, longitude) float64 dask.array<chunksize=(12, 201, 481), meta=np.ndarray>
    t_anom_10D     (date, latitude, longitude) float64 dask.array<chunksize=(12, 201, 481), meta=np.ndarray>
    t_clmt         (date, latitude, longitude) float64 dask.array<chunksize=(12, 201, 481), meta=np.ndarray>
    u              (date, latitude, longitude) float64 dask.array<chunksize=(12, 201, 481), meta=np.ndarray>
    u_anom_10D     (date, la

12 dates have been written for Apr_negbg1_decay_ql_xy_z_v2.csv


In [50]:
1

1

In [66]:
ds_brnch2.isel(date=0).drop(['number','step','strftime','dates_roll_clmt'])\
                    [['u','v','u_anom_10D','v_anom_10D','z_anom_10D','dse_anom', 'dse_anom_Lag1']].compute()

/home/lab_hardik/my_conda/lib/python3.9/site-packages/distributed/client.py:3357: UserWarning: Sending large graph of size 487.97 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.


<xarray.Dataset>
Dimensions:        (latitude: 201, longitude: 481)
Coordinates:
  * latitude       (latitude) float64 10.0 10.25 10.5 10.75 ... 59.5 59.75 60.0
  * longitude      (longitude) float64 0.0 0.25 0.5 0.75 ... 119.5 119.8 120.0
    date           datetime64[ns] 1983-04-08
Data variables:
    u              (latitude, longitude) float64 -2.236 -2.333 ... -3.804 -3.682
    v              (latitude, longitude) float64 -2.582 -2.758 ... 2.838 2.797
    u_anom_10D     (latitude, longitude) float64 -0.4019 -0.5656 ... -8.651
    v_anom_10D     (latitude, longitude) float64 -2.256 -2.348 ... 4.394 4.339
    z_anom_10D     (latitude, longitude) float64 -35.96 -36.47 ... 18.21 27.79
    dse_anom       (latitude, longitude) float64 1.24e+03 ... 3.483e+03
    dse_anom_Lag1  (latitude, longitude) float64 1.335e+03 ... 2.985e+03

In [ ]:
existing_nc_lst.sort()

In [47]:
existing_nc_lst

['Apr_negbg_amplif_ql_xy_v2_1983_04_08_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_1983_04_09_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_1986_04_26_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_1986_04_27_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_1987_04_09_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_1989_04_24_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_1996_04_07_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_2009_04_07_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_2011_04_17_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_2011_04_18_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_2015_04_04_2Dave.nc',
 'Apr_negbg_amplif_ql_xy_v2_2018_04_20_2Dave.nc']

In [49]:
gc.collect()

0